package application;

public enum SortType {
	CREATED_ASCENDING, CREATED_DESCENDING, STATUS_ASCENDING, STATUS_DESCENDING, COMPLETED_ASCENDING,
	COMPLETED_DESCENDING, TECHNICIAN_ASCENDING, TECHNICIAN_DESCENDING;
}